making the binary executable on device
larq/docs pull request #278
Opened 2021-06-17 20:17 UTC by rameshKrSah

Earlier the lce_benchmark_model binary was made executable and then transferred to the device (Android phones) and this was failing on Windows. Now, the binary is made executable on the device and it runs as expected.

2021-06-17 20:43 UTC, lgeiger requested changes
Great! Thanks for the PR 🎉 

Just one minor comment below.

2021-06-17 20:43 UTC, lgeiger commented on docs/compute-engine/benchmark.md
> +       adb shell +x /data/local/tmp/lce_benchmark_model
Shouldn't this be:
```suggestion
       adb shell chmod +x /data/local/tmp/lce_benchmark_model
```

2021-06-18 05:22 UTC, rameshKrSah commented on docs/compute-engine/benchmark.md
> +       adb shell +x /data/local/tmp/lce_benchmark_model
Yeah. Sorry forgot the main part.

2021-06-18 05:26 UTC, rameshKrSah reviewed
I approved the changes

2021-06-18 07:04 UTC, Tombana approved these changes

2021-06-18 10:16 UTC, lgeiger approved these changes
Great! thanks for the fix 🚀

2021-06-18 10:16 UTC, lgeiger commented on docs/compute-engine/benchmark.md
> +
```suggestion

```

2021-06-18 10:17 UTC, lgeiger approved these changes

2021-06-18 10:17 UTC, lgeiger commented on docs/compute-engine/benchmark.md
> +    6. Transfer the converted `.tflite` model file to your phone:
```suggestion

    6. Transfer the converted `.tflite` model file to your phone:
```

2021-06-18 10:25 UTC, merged